# Copyright (c) 2026 ARARAT33. Based on AWEAI. All rights reserved.
"""AWEAI wiki generator with multi-layer watermarking.

Builds the full Markdown wiki under ``docs/wiki/`` — one page per command
group plus a home page — covering every CLI command with description,
usage and examples. Run with ``aweai wiki build``.
"""

from __future__ import annotations

import datetime
import json
from pathlib import Path
from typing import Any, Dict, List

from aweai.watermark import AWEAIWatermarkEngine

HEADER = """# AWEAI Wiki

> Universal CLI for AI/ASI/AGI engineering — pure terminal, no UI.
> Copyright (c) 2026 **ARARAT33** — based on **AWEAI**. All rights reserved.

"""
FOOTER = """

---
*Generated by `aweai wiki build` on {date}. Copyright (c) 2026 ARARAT33 — based on AWEAI.*
"""


def _group_page(group: str, commands: List[Dict[str, str]], max_specs: int) -> str:
    lines = [f"# {group} commands", ""]
    lines.append(f"Total commands: **{len(commands)}**")
    lines.append("")
    lines.append("| Command | Description |")
    lines.append("| --- | --- |")
    for c in commands:
        lines.append(f"| `{c['command']}` | {c['help'][:90]} |")
    lines.append("")
    content = "\n".join(lines)
    engine = AWEAIWatermarkEngine()
    return engine.embed_text(content, payload=f"WIKI_PAGE[{group}]")


def _spec_page(group: str, specs: List[Dict[str, Any]], max_specs: int) -> str:
    lines = [f"# `aweai {group}` — utility commands", ""]
    lines.append(f"Group: **{group}** — {len(specs)} commands.")
    lines.append("")
    for spec in specs[:max_specs]:
        name = spec["name"]
        lines.append(f"## `aweai {group} {name}`")
        lines.append("")
        lines.append(f"**{spec['help']}**")
        lines.append("")
        if spec["params"]:
            lines.append("**Parameters:**")
            lines.append("")
            lines.append("| Flag | Default | Description |")
            lines.append("| --- | --- | --- |")
            for pname, default, phelp in spec["params"]:
                lines.append(f"| `--{pname}` | `{default}` | {phelp} |")
            lines.append("")
            first = spec["params"][0]
            if first[1] != "" and first[1] is not None:
                example_val = str(first[1]).split(",")[0]
                lines.append("**Example:**")
                lines.append("")
                lines.append(f"```bash")
                lines.append(f"aweai {group} {name} --{first[0]} {example_val}")
                lines.append(f"```")
                lines.append("")
    content = "\n".join(lines)
    engine = AWEAIWatermarkEngine()
    return engine.embed_text(content, payload=f"WIKI_SPEC[{group}]")


def build_wiki(out_dir: str = "docs/wiki", max_specs: int = 500) -> Dict[str, Any]:
    """Generate watermarked wiki pages for all groups."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    from aweai import bulk
    from aweai.cli import _flatten_commands, app

    # Sub-app groups (domain)
    domain_groups = {g.name: g.typer_instance for g in app.registered_groups}
    pages = 0
    for gname, gapp in domain_groups.items():
        cmds = _flatten_commands(gapp)
        page = _group_page(gname, cmds, max_specs)
        (out / f"commands-{gname}.md").write_text(page, encoding="utf-8")
        pages += 1

    # Bulk spec groups
    for gname in bulk.groups():
        specs = bulk.specs_for(gname)
        page = _spec_page(gname, specs, max_specs)
        (out / f"commands-{gname}.md").write_text(page, encoding="utf-8")
        pages += 1

    # Core commands page
    from aweai.cli import app

    core = [c for c in app.registered_commands]
    core_page = ["# Core commands", "", f"Total: **{len(core)}**", ""]
    for c in core:
        name = c.name or c.callback.__name__
        core_page.append(f"## `aweai {name}`")
        core_page.append("")
        core_page.append(f"{(c.help or c.callback.__doc__ or '').strip()}")
        core_page.append("")

    engine = AWEAIWatermarkEngine()
    core_content = engine.embed_text("\n".join(core_page), payload="WIKI_CORE")
    (out / "commands-core.md").write_text(core_content, encoding="utf-8")
    pages += 1

    return {"pages": pages, "out_dir": str(out), "groups": len(domain_groups) + len(bulk.groups()), "watermarked": True}


def build_wiki_index(out_dir: str = "docs/wiki") -> Dict[str, Any]:
    """Generate the watermarked wiki home page (index)."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    from aweai import __version__, bulk

    lines = [f"# AWEAI Wiki v{__version__}", ""]
    lines.append("> Universal CLI for AI/ASI/AGI engineering — pure terminal, no UI.")
    lines.append("> Copyright (c) 2026 **ARARAT33** — based on **AWEAI**. All rights reserved.")
    lines.append("")
    lines.append("## Command groups")
    lines.append("")
    lines.append("| Group | Description | Page |")
    lines.append("| --- | --- | --- |")
    lines.append("| `collect` | Data collection: scraping, crawling, import/export, cleaning, synthetic data | [commands-collect](commands-collect.md) |")
    lines.append("| `data` | Data management: datasets, pipelines, preprocessing, tokenization, embedding | [commands-data](commands-data.md) |")
    lines.append("| `model` | Models: train/eval/manage 16+ types, fine-tune, quantize, export | [commands-model](commands-model.md) |")
    lines.append("| `providers` | Providers & integrations: API keys, external models, fine-tuning | [commands-providers](commands-providers.md) |")
    lines.append("| `devices` | Devices & servers: SSH, remote, cluster, distributed training | [commands-devices](commands-devices.md) |")
    lines.append("| `ops` | Operations: users, auth, billing, workflows, schedulers, AGI, RAG, security | [commands-ops](commands-ops.md) |")
    lines.append("| `ai` | AI/ASI/AGI knowledge base, roadmap, concepts | [commands-ai](commands-ai.md) |")
    lines.append("| `commands` | Inspect the AWEAI command universe | [commands-commands](commands-commands.md) |")
    lines.append("| `wiki` | Generate this wiki | [commands-wiki](commands-wiki.md) |")
    for g in bulk.groups():
        lines.append(f"| `{g}` | {g} utilities ({len(bulk.specs_for(g))} commands) | [commands-{g}](commands-{g}.md) |")
    lines.append("")
    lines.append(f"Total bulk utility commands: **{bulk.count()}** in {len(bulk.groups())} groups.")
    lines.append("")
    lines.append("## Core commands")
    lines.append("")
    lines.append("| Command | Description |")
    lines.append("| --- | --- |")
    lines.append("| `train` | Train a model from scratch |")
    lines.append("| `eval` | Evaluate a model |")
    lines.append("| `export` | Export a model |")
    lines.append("| `quantize` | Quantize a model |")
    lines.append("| `market` | Model marketplace |")
    lines.append("| `rag` | RAG index/ask |")
    lines.append("| `actions` | Natural-language actions |")
    lines.append("| `autotest` | Full system self-check |")
    lines.append("| `tools` | Extension toolkit (1000+ tools) |")
    lines.append("| `ai` | AI/ASI/AGI knowledge |")
    lines.append("| `commands` | Command registry |")
    lines.append("| `wiki build` | Generate this wiki |")
    lines.append("")
    lines.append("See [commands-core](commands-core.md) for the full list.")
    lines.append("")

    engine = AWEAIWatermarkEngine()
    home_content = engine.embed_text("\n".join(lines), payload="WIKI_HOME")
    (out / "Home.md").write_text(home_content, encoding="utf-8")
    return {"page": "Home.md", "out_dir": str(out), "watermarked": True}
