"""AWEAI codegen tools — code generation, refactoring, linting, docs.

Each tool has a unique purpose and works offline (template/scaffold based).
"""

from __future__ import annotations

import ast
import json
import re
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional

from aweai.tools.registry import tool


@tool("codegen_function", "codegen", "Generate a Python function stub from a signature")
def codegen_function(name: str = "my_function", params: str = "x", returns: str = "None", doc: str = "") -> Dict[str, Any]:
    code = f"def {name}({params}):\n    \"\"\"{doc or 'Auto-generated function.'}\"\"\"\n    return {returns}\n"
    return {"code": code, "language": "python"}


@tool("codegen_class", "codegen", "Generate a Python class stub")
def codegen_class(name: str = "MyClass", methods: str = '["__init__", "run"]') -> Dict[str, Any]:
    methods_list = json.loads(methods) if isinstance(methods, str) else methods
    lines = [f"class {name}:\n"]
    for m in methods_list:
        lines.append(f"    def {m}(self, *args, **kwargs):\n        \"\"\"Method {m}.\"\"\"\n        raise NotImplementedError\n")
    return {"code": "\n".join(lines), "language": "python"}


@tool("codegen_json_schema", "codegen", "Generate a JSON schema draft for a list of fields")
def codegen_json_schema(fields: str = '["id", "name", "value"]') -> Dict[str, Any]:
    flds = json.loads(fields) if isinstance(fields, str) else fields
    props = {f: {"type": "string"} for f in flds}
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": props,
        "required": flds,
    }
    return {"schema": schema}


@tool("codegen_bash_script", "codegen", "Generate a safe bash script header + echo")
def codegen_bash_script(name: str = "script.sh", body: str = "echo hello") -> Dict[str, Any]:
    code = f"#!/usr/bin/env bash\n# {name} — generated by AWEAI\nset -euo pipefail\n\n{body}\n"
    return {"code": code, "language": "bash"}


@tool("codegen_html_page", "codegen", "Generate a minimal responsive HTML page")
def codegen_html_page(title: str = "AWEAI Page", body: str = "<p>Hello</p>") -> Dict[str, Any]:
    code = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>body{{font-family:sans-serif;max-width:800px;margin:auto;padding:1rem}}</style>
</head>
<body>
<h1>{title}</h1>
{body}
</body>
</html>
"""
    return {"code": code, "language": "html"}


@tool("codegen_readme", "codegen", "Generate a README skeleton from a project name and features")
def codegen_readme(name: str = "my-project", features: str = '["feature A", "feature B"]') -> Dict[str, Any]:
    feats = json.loads(features) if isinstance(features, str) else features
    bullets = "\n".join(f"- {f}" for f in feats)
    readme = f"""# {name}

## Features
{bullets}

## Install
```bash
pip install -e .
```

## Usage
```bash
{name} --help
```

## License
MIT
"""
    return {"code": readme, "language": "markdown"}


@tool("codegen_gitignore", "codegen", "Generate a Python .gitignore")
def codegen_gitignore() -> Dict[str, Any]:
    content = """__pycache__/
*.py[cod]
*.egg-info/
.venv/
venv/
dist/
build/
.pytest_cache/
.coverage
*.db
*.sqlite3
.env
"""
    return {"code": content, "language": "gitignore"}


@tool("codegen_requirements", "codegen", "Generate a requirements.txt from a package list")
def codegen_requirements(packages: str = '["numpy", "requests"]') -> Dict[str, Any]:
    pkgs = json.loads(packages) if isinstance(packages, str) else packages
    return {"code": "\n".join(pkgs), "language": "txt", "packages": len(pkgs)}


@tool("codegen_makefile", "codegen", "Generate a simple Makefile")
def codegen_makefile(project: str = "app") -> Dict[str, Any]:
    content = f""".PHONY: test install run clean

test:
\tpython -m pytest -q

install:
\tpip install -e .

run:
\tpython -m {project}

clean:
\trm -rf build dist *.egg-info __pycache__
"""
    return {"code": content, "language": "makefile"}


@tool("codegen_dockerfile", "codegen", "Generate a Python Dockerfile")
def codegen_dockerfile(base: str = "python:3.11-slim") -> Dict[str, Any]:
    content = f"""FROM {base}
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "-m", "aweai", "serve", "--host", "0.0.0.0"]
"""
    return {"code": content, "language": "dockerfile"}


@tool("codegen_ci_workflow", "codegen", "Generate a GitHub Actions CI workflow")
def codegen_ci_workflow(python: str = "3.11") -> Dict[str, Any]:
    content = f"""name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '{python}'
      - run: pip install -e .
      - run: python -m pytest -q
"""
    return {"code": content, "language": "yaml"}


@tool("codegen_cli", "codegen", "Generate a typer/click CLI skeleton")
def codegen_cli(name: str = "mycli", commands: str = '["hello", "run"]') -> Dict[str, Any]:
    cmds = json.loads(commands) if isinstance(commands, str) else commands
    lines = ["import typer", "", "app = typer.Typer()", ""]
    for c in cmds:
        lines.append(f'@app.command()\ndef {c}(name: str = typer.Argument("world")):\n    """Command {c}."""\n    typer.echo(f"{{name}} from {c}")')
        lines.append("")
    lines.append('if __name__ == "__main__":\n    app()')
    return {"code": "\n".join(lines), "language": "python"}


@tool("codegen_init", "codegen", "Generate a Python package __init__.py with version")
def codegen_init(name: str = "mypkg", version: str = "0.1.0") -> Dict[str, Any]:
    return {"code": f'"""The {name} package."""\n\n__version__ = "{version}"\n', "language": "python"}


@tool("codegen_pyproject", "codegen", "Generate a pyproject.toml skeleton")
def codegen_pyproject(name: str = "mypkg", version: str = "0.1.0") -> Dict[str, Any]:
    content = f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "{version}"
description = "Generated by AWEAI"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["{name}*"]
"""
    return {"code": content, "language": "toml"}


@tool("codegen_test_file", "codegen", "Generate a pytest test file for a module")
def codegen_test_file(module: str = "my_module", functions: str = '["add", "sub"]') -> Dict[str, Any]:
    fns = json.loads(functions) if isinstance(functions, str) else functions
    lines = [f"from {module} import " + ", ".join(fns), "", ""]
    for fn in fns:
        lines.append(f"def test_{fn}():\n    result = {fn}(1, 2)\n    assert result is not None\n")
    return {"code": "\n".join(lines), "language": "python"}


@tool("codegen_fastapi", "codegen", "Generate a FastAPI app skeleton")
def codegen_fastapi(name: str = "app") -> Dict[str, Any]:
    content = f'''"""{name} — FastAPI app generated by AWEAI."""
from fastapi import FastAPI

app = FastAPI(title="{name}")


@app.get("/")
def root():
    return {{"status": "ok", "name": "{name}"}}


@app.get("/health")
def health():
    return {{"status": "healthy"}}
'''
    return {"code": content, "language": "python"}


@tool("lint_python_syntax", "codegen", "Check Python file syntax via ast.parse")
def lint_python_syntax(path: str) -> Dict[str, Any]:
    try:
        ast.parse(Path(path).read_text(encoding="utf-8"))
        return {"path": path, "valid": True}
    except SyntaxError as e:
        return {"path": path, "valid": False, "error": str(e)}


@tool("lint_python_compile", "codegen", "Compile a Python file (py_compile) and report errors")
def lint_python_compile(path: str) -> Dict[str, Any]:
    import py_compile

    try:
        py_compile.compile(path, doraise=True)
        return {"path": path, "compiled": True}
    except py_compile.PyCompileError as e:
        return {"path": path, "compiled": False, "error": str(e)}


@tool("code_metrics", "codegen", "Basic code metrics of a Python file (lines, functions, classes)")
def code_metrics(path: str) -> Dict[str, Any]:
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    tree = ast.parse(text)
    funcs = sum(1 for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)))
    classes = sum(1 for n in ast.walk(tree) if isinstance(n, ast.ClassDef))
    return {
        "path": path,
        "lines": len(text.splitlines()),
        "chars": len(text),
        "functions": funcs,
        "classes": classes,
        "imports": sum(1 for n in ast.walk(tree) if isinstance(n, (ast.Import, ast.ImportFrom))),
    }


@tool("code_count_lines", "codegen", "Count total lines of code for a directory (python files)")
def code_count_lines(root: str = ".") -> Dict[str, Any]:
    total = 0
    files = 0
    for p in Path(root).rglob("*.py"):
        if "__pycache__" in str(p) or ".venv" in str(p):
            continue
        try:
            total += len(p.read_text(encoding="utf-8", errors="replace").splitlines())
            files += 1
        except Exception:
            continue
    return {"root": root, "files": files, "lines": total}


@tool("refactor_rename", "codegen", "Rename an identifier in a text/code (token-level)")
def refactor_rename(code: str, old: str, new: str) -> Dict[str, Any]:
    if not old:
        return {"error": "old name required"}
    pattern = re.compile(rf"\b{re.escape(old)}\b")
    return {"code": pattern.sub(new, code), "replacements": len(pattern.findall(code))}


@tool("refactor_strip_comments", "codegen", "Remove Python comments from source text (naive)")
def refactor_strip_comments(code: str) -> Dict[str, Any]:
    lines = []
    for line in code.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        idx = line.find(" #")
        lines.append(line[:idx] if idx >= 0 else line)
    return {"code": "\n".join(lines)}


@tool("refactor_dedupe_lines", "codegen", "Remove duplicate consecutive lines from text")
def refactor_dedupe_lines(text: str) -> Dict[str, Any]:
    out = []
    prev = None
    removed = 0
    for line in text.splitlines():
        if line == prev:
            removed += 1
            continue
        out.append(line)
        prev = line
    return {"text": "\n".join(out), "removed": removed}


@tool("docstring_generate", "codegen", "Generate a docstring skeleton for a function signature")
def docstring_generate(signature: str = "def f(x, y):") -> Dict[str, Any]:
    m = re.match(r"def\s+(\w+)\s*\((.*?)\)", signature)
    if not m:
        return {"error": "invalid signature"}
    name, params = m.group(1), m.group(2)
    param_lines = "\n".join(f"    {p.strip()}:" for p in params.split(",") if p.strip())
    doc = f'"""\n{name}.\n\nArgs:\n{param_lines}\n\nReturns:\n    \n"""'
    return {"docstring": doc}


@tool("changelog_generate", "codegen", "Generate a CHANGELOG skeleton from a version and features")
def changelog_generate(version: str = "v1.0.0", features: str = '["init"]') -> Dict[str, Any]:
    feats = json.loads(features) if isinstance(features, str) else features
    lines = [f"## {version}", ""]
    lines += [f"- {f}" for f in feats]
    return {"changelog": "\n".join(lines)}


@tool("markdown_table", "codegen", "Convert a JSON array of objects to a markdown table")
def markdown_table(rows: str) -> Dict[str, Any]:
    data = json.loads(rows) if isinstance(rows, str) else rows
    if not data or not isinstance(data[0], dict):
        return {"error": "rows must be a non-empty JSON array of objects"}
    headers = list(data[0].keys())
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in data:
        lines.append("| " + " | ".join(str(row.get(h, "")) for h in headers) + " |")
    return {"table": "\n".join(lines)}


@tool("json_to_yaml_hint", "codegen", "Convert JSON to a YAML-ish representation (no dependency)")
def json_to_yaml_hint(data: str) -> Dict[str, Any]:
    obj = json.loads(data) if isinstance(data, str) else data
    lines = []

    def render(o, indent=0):
        pad = "  " * indent
        if isinstance(o, dict):
            for k, v in o.items():
                if isinstance(v, (dict, list)):
                    lines.append(f"{pad}{k}:")
                    render(v, indent + 1)
                else:
                    lines.append(f"{pad}{k}: {v}")
        elif isinstance(o, list):
            for v in o:
                if isinstance(v, (dict, list)):
                    render(v, indent)
                else:
                    lines.append(f"{pad}- {v}")

    render(obj)
    return {"yaml": "\n".join(lines)}


@tool("template_apply", "codegen", "Apply simple {{var}} substitutions to a template string")
def template_apply(template: str, variables: str = "{}") -> Dict[str, Any]:
    vars_data = json.loads(variables) if isinstance(variables, str) else variables
    out = template
    for k, v in vars_data.items():
        out = out.replace("{{" + k + "}}", str(v))
    return {"rendered": out}


__all__ = []
